apiVersion: v1
kind: ConfigMap
metadata:
  name: tempo-config
  namespace: tempons
  labels:
    app: tempo
    component: config
  annotations:
    description: Tempo configuration file
    version: "1.0"
data:
  tempo.yaml: |
    server:
      http_listen_port: 3200

    distributor:
      receivers:
        otlp:
          protocols:
            http:
              endpoint: "0.0.0.0:4317"
            grpc:
              endpoint: "0.0.0.0:4318"

    compactor:
      compaction:
        block_retention: 48h

    metrics_generator:
      registry:
        external_labels:
          source: tempo
          cluster: linux-microservices
      storage:
        path: /var/tempo/generator/wal
        remote_write:
          - url: http://prometheus-service.monitoring.svc.cluster.local:9090/api/v1/write
            send_exemplars: true

    storage:
      trace:
        backend: s3
        s3:
          endpoint: my-minio-fs-service.minio.svc.cluster.local:9000
          bucket: grafana-traces-data
          forcepathstyle: true
          insecure: true
          access_key: "minio" # Replace with actual access key
          secret_key: "minio123" # Replace with actual secret key
        wal:
          path: /var/tempo/wal
        local:
          path: /var/tempo/blocks

    overrides:
      defaults:
        metrics_generator:
          processors: [service-graphs, span-metrics]