apiVersion: v1
kind: Service
metadata:
  name: tempo
  namespace: tempons
  labels:
    app: tempo
spec:
  ports:
    - name: otlphttp
      port: 4317
      targetPort: 4317
        #nodePort: 30148
    - name: otlgrpc
      port: 4318
      targetPort: 4318
    - name: container
      port: 3200
      targetPort: 3200
  selector:
    app: tempo